# Generated by Django 3.0.6 on 2020-05-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(db_column='userId', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=20, unique=True)),
                ('password', models.CharField(db_column='userPassword', max_length=256)),
            ],
            options={
                'db_table': 'user_entity',
            },
        ),
    ]
