# Generated by Django 3.0.6 on 2020-05-28 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(db_column='userId', primary_key=True, serialize=False)),
                ('user', models.CharField(db_column='user', max_length=20, unique=True)),
                ('date', models.DateTimeField(db_column='date', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user_entity',
            },
        ),
    ]
