# Generated by Django 3.0.6 on 2020-05-28 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeLabsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date',
            field=models.DateTimeField(db_column='date', default=datetime.date.today),
        ),
    ]
