# Generated by Django 3.0.6 on 2020-05-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeLabsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(db_column='activeStatus', default=True),
        ),
    ]
