# Generated by Django 3.0.6 on 2020-05-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeLabsApp', '0002_auto_20200528_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='password',
        ),
    ]
